### ISSUE TITLE
Relationship?

### ISSUE THREAD

**Issue by johanbech** [erossini/MyTicket#1]
Hi erossini.
Have you make with relationship like between two tables? if do where in code can i find or what will you do to make it, and test it?

Im just need to go on with that THX

Johan

**Comment by erossini** [comment]
Hi,
in this project I don't have any relationship between tables. You can have some examples in my other project [AdminLTEWithASPNETCore](https://github.com/erossini/AdminLTEWithASPNETCore). The persistent has a lot of relationship.

Also, you have a list of articles about Entity Framework that can help you on [PureSourceCode](https://www.puresourcecode.com/dotnet/net-core/create-database-from-model-using-efcore/).
